// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_or1k_i_adr_i,
    input  [31:0] wb_or1k_i_dat_i,
    input   [3:0] wb_or1k_i_sel_i,
    input         wb_or1k_i_we_i,
    input         wb_or1k_i_cyc_i,
    input         wb_or1k_i_stb_i,
    input   [2:0] wb_or1k_i_cti_i,
    input   [1:0] wb_or1k_i_bte_i,
    output [31:0] wb_or1k_i_dat_o,
    output        wb_or1k_i_ack_o,
    output        wb_or1k_i_err_o,
    output        wb_or1k_i_rty_o,
    input  [31:0] wb_or1k_d_adr_i,
    input  [31:0] wb_or1k_d_dat_i,
    input   [3:0] wb_or1k_d_sel_i,
    input         wb_or1k_d_we_i,
    input         wb_or1k_d_cyc_i,
    input         wb_or1k_d_stb_i,
    input   [2:0] wb_or1k_d_cti_i,
    input   [1:0] wb_or1k_d_bte_i,
    output [31:0] wb_or1k_d_dat_o,
    output        wb_or1k_d_ack_o,
    output        wb_or1k_d_err_o,
    output        wb_or1k_d_rty_o,
    input  [31:0] wb_dbg_adr_i,
    input  [31:0] wb_dbg_dat_i,
    input   [3:0] wb_dbg_sel_i,
    input         wb_dbg_we_i,
    input         wb_dbg_cyc_i,
    input         wb_dbg_stb_i,
    input   [2:0] wb_dbg_cti_i,
    input   [1:0] wb_dbg_bte_i,
    output [31:0] wb_dbg_dat_o,
    output        wb_dbg_ack_o,
    output        wb_dbg_err_o,
    output        wb_dbg_rty_o,
    output [31:0] wb_uart0_adr_o,
    output  [7:0] wb_uart0_dat_o,
    output  [3:0] wb_uart0_sel_o,
    output        wb_uart0_we_o,
    output        wb_uart0_cyc_o,
    output        wb_uart0_stb_o,
    output  [2:0] wb_uart0_cti_o,
    output  [1:0] wb_uart0_bte_o,
    input   [7:0] wb_uart0_dat_i,
    input         wb_uart0_ack_i,
    input         wb_uart0_err_i,
    input         wb_uart0_rty_i,
    output [31:0] wb_gpio0_adr_o,
    output  [7:0] wb_gpio0_dat_o,
    output  [3:0] wb_gpio0_sel_o,
    output        wb_gpio0_we_o,
    output        wb_gpio0_cyc_o,
    output        wb_gpio0_stb_o,
    output  [2:0] wb_gpio0_cti_o,
    output  [1:0] wb_gpio0_bte_o,
    input   [7:0] wb_gpio0_dat_i,
    input         wb_gpio0_ack_i,
    input         wb_gpio0_err_i,
    input         wb_gpio0_rty_i,
    output [31:0] wb_switch0_adr_o,
    output  [7:0] wb_switch0_dat_o,
    output  [3:0] wb_switch0_sel_o,
    output        wb_switch0_we_o,
    output        wb_switch0_cyc_o,
    output        wb_switch0_stb_o,
    output  [2:0] wb_switch0_cti_o,
    output  [1:0] wb_switch0_bte_o,
    input   [7:0] wb_switch0_dat_i,
    input         wb_switch0_ack_i,
    input         wb_switch0_err_i,
    input         wb_switch0_rty_i,
    output [31:0] wb_switch1_adr_o,
    output  [7:0] wb_switch1_dat_o,
    output  [3:0] wb_switch1_sel_o,
    output        wb_switch1_we_o,
    output        wb_switch1_cyc_o,
    output        wb_switch1_stb_o,
    output  [2:0] wb_switch1_cti_o,
    output  [1:0] wb_switch1_bte_o,
    input   [7:0] wb_switch1_dat_i,
    input         wb_switch1_ack_i,
    input         wb_switch1_err_i,
    input         wb_switch1_rty_i,
    output [31:0] wb_switch2_adr_o,
    output  [7:0] wb_switch2_dat_o,
    output  [3:0] wb_switch2_sel_o,
    output        wb_switch2_we_o,
    output        wb_switch2_cyc_o,
    output        wb_switch2_stb_o,
    output  [2:0] wb_switch2_cti_o,
    output  [1:0] wb_switch2_bte_o,
    input   [7:0] wb_switch2_dat_i,
    input         wb_switch2_ack_i,
    input         wb_switch2_err_i,
    input         wb_switch2_rty_i,
    output [31:0] wb_key_adr_o,
    output  [7:0] wb_key_dat_o,
    output  [3:0] wb_key_sel_o,
    output        wb_key_we_o,
    output        wb_key_cyc_o,
    output        wb_key_stb_o,
    output  [2:0] wb_key_cti_o,
    output  [1:0] wb_key_bte_o,
    input   [7:0] wb_key_dat_i,
    input         wb_key_ack_i,
    input         wb_key_err_i,
    input         wb_key_rty_i,
    output [31:0] wb_ledr0_adr_o,
    output  [7:0] wb_ledr0_dat_o,
    output  [3:0] wb_ledr0_sel_o,
    output        wb_ledr0_we_o,
    output        wb_ledr0_cyc_o,
    output        wb_ledr0_stb_o,
    output  [2:0] wb_ledr0_cti_o,
    output  [1:0] wb_ledr0_bte_o,
    input   [7:0] wb_ledr0_dat_i,
    input         wb_ledr0_ack_i,
    input         wb_ledr0_err_i,
    input         wb_ledr0_rty_i,
    output [31:0] wb_ledr1_adr_o,
    output  [7:0] wb_ledr1_dat_o,
    output  [3:0] wb_ledr1_sel_o,
    output        wb_ledr1_we_o,
    output        wb_ledr1_cyc_o,
    output        wb_ledr1_stb_o,
    output  [2:0] wb_ledr1_cti_o,
    output  [1:0] wb_ledr1_bte_o,
    input   [7:0] wb_ledr1_dat_i,
    input         wb_ledr1_ack_i,
    input         wb_ledr1_err_i,
    input         wb_ledr1_rty_i,
    output [31:0] wb_ledg0_adr_o,
    output  [7:0] wb_ledg0_dat_o,
    output  [3:0] wb_ledg0_sel_o,
    output        wb_ledg0_we_o,
    output        wb_ledg0_cyc_o,
    output        wb_ledg0_stb_o,
    output  [2:0] wb_ledg0_cti_o,
    output  [1:0] wb_ledg0_bte_o,
    input   [7:0] wb_ledg0_dat_i,
    input         wb_ledg0_ack_i,
    input         wb_ledg0_err_i,
    input         wb_ledg0_rty_i,
    output [31:0] wb_ledgr0_adr_o,
    output  [7:0] wb_ledgr0_dat_o,
    output  [3:0] wb_ledgr0_sel_o,
    output        wb_ledgr0_we_o,
    output        wb_ledgr0_cyc_o,
    output        wb_ledgr0_stb_o,
    output  [2:0] wb_ledgr0_cti_o,
    output  [1:0] wb_ledgr0_bte_o,
    input   [7:0] wb_ledgr0_dat_i,
    input         wb_ledgr0_ack_i,
    input         wb_ledgr0_err_i,
    input         wb_ledgr0_rty_i,
    output [31:0] wb_rom0_adr_o,
    output [31:0] wb_rom0_dat_o,
    output  [3:0] wb_rom0_sel_o,
    output        wb_rom0_we_o,
    output        wb_rom0_cyc_o,
    output        wb_rom0_stb_o,
    output  [2:0] wb_rom0_cti_o,
    output  [1:0] wb_rom0_bte_o,
    input  [31:0] wb_rom0_dat_i,
    input         wb_rom0_ack_i,
    input         wb_rom0_err_i,
    input         wb_rom0_rty_i,
    output [31:0] wb_sdram_dbus_adr_o,
    output [31:0] wb_sdram_dbus_dat_o,
    output  [3:0] wb_sdram_dbus_sel_o,
    output        wb_sdram_dbus_we_o,
    output        wb_sdram_dbus_cyc_o,
    output        wb_sdram_dbus_stb_o,
    output  [2:0] wb_sdram_dbus_cti_o,
    output  [1:0] wb_sdram_dbus_bte_o,
    input  [31:0] wb_sdram_dbus_dat_i,
    input         wb_sdram_dbus_ack_i,
    input         wb_sdram_dbus_err_i,
    input         wb_sdram_dbus_rty_i,
    output [31:0] wb_sdram_ibus_adr_o,
    output [31:0] wb_sdram_ibus_dat_o,
    output  [3:0] wb_sdram_ibus_sel_o,
    output        wb_sdram_ibus_we_o,
    output        wb_sdram_ibus_cyc_o,
    output        wb_sdram_ibus_stb_o,
    output  [2:0] wb_sdram_ibus_cti_o,
    output  [1:0] wb_sdram_ibus_bte_o,
    input  [31:0] wb_sdram_ibus_dat_i,
    input         wb_sdram_ibus_ack_i,
    input         wb_sdram_ibus_err_i,
    input         wb_sdram_ibus_rty_i);

wire [31:0] wb_m2s_or1k_d_sdram_dbus_adr;
wire [31:0] wb_m2s_or1k_d_sdram_dbus_dat;
wire  [3:0] wb_m2s_or1k_d_sdram_dbus_sel;
wire        wb_m2s_or1k_d_sdram_dbus_we;
wire        wb_m2s_or1k_d_sdram_dbus_cyc;
wire        wb_m2s_or1k_d_sdram_dbus_stb;
wire  [2:0] wb_m2s_or1k_d_sdram_dbus_cti;
wire  [1:0] wb_m2s_or1k_d_sdram_dbus_bte;
wire [31:0] wb_s2m_or1k_d_sdram_dbus_dat;
wire        wb_s2m_or1k_d_sdram_dbus_ack;
wire        wb_s2m_or1k_d_sdram_dbus_err;
wire        wb_s2m_or1k_d_sdram_dbus_rty;
wire [31:0] wb_m2s_or1k_d_uart0_adr;
wire [31:0] wb_m2s_or1k_d_uart0_dat;
wire  [3:0] wb_m2s_or1k_d_uart0_sel;
wire        wb_m2s_or1k_d_uart0_we;
wire        wb_m2s_or1k_d_uart0_cyc;
wire        wb_m2s_or1k_d_uart0_stb;
wire  [2:0] wb_m2s_or1k_d_uart0_cti;
wire  [1:0] wb_m2s_or1k_d_uart0_bte;
wire [31:0] wb_s2m_or1k_d_uart0_dat;
wire        wb_s2m_or1k_d_uart0_ack;
wire        wb_s2m_or1k_d_uart0_err;
wire        wb_s2m_or1k_d_uart0_rty;
wire [31:0] wb_m2s_or1k_d_gpio0_adr;
wire [31:0] wb_m2s_or1k_d_gpio0_dat;
wire  [3:0] wb_m2s_or1k_d_gpio0_sel;
wire        wb_m2s_or1k_d_gpio0_we;
wire        wb_m2s_or1k_d_gpio0_cyc;
wire        wb_m2s_or1k_d_gpio0_stb;
wire  [2:0] wb_m2s_or1k_d_gpio0_cti;
wire  [1:0] wb_m2s_or1k_d_gpio0_bte;
wire [31:0] wb_s2m_or1k_d_gpio0_dat;
wire        wb_s2m_or1k_d_gpio0_ack;
wire        wb_s2m_or1k_d_gpio0_err;
wire        wb_s2m_or1k_d_gpio0_rty;
wire [31:0] wb_m2s_or1k_d_key_adr;
wire [31:0] wb_m2s_or1k_d_key_dat;
wire  [3:0] wb_m2s_or1k_d_key_sel;
wire        wb_m2s_or1k_d_key_we;
wire        wb_m2s_or1k_d_key_cyc;
wire        wb_m2s_or1k_d_key_stb;
wire  [2:0] wb_m2s_or1k_d_key_cti;
wire  [1:0] wb_m2s_or1k_d_key_bte;
wire [31:0] wb_s2m_or1k_d_key_dat;
wire        wb_s2m_or1k_d_key_ack;
wire        wb_s2m_or1k_d_key_err;
wire        wb_s2m_or1k_d_key_rty;
wire [31:0] wb_m2s_or1k_d_ledr0_adr;
wire [31:0] wb_m2s_or1k_d_ledr0_dat;
wire  [3:0] wb_m2s_or1k_d_ledr0_sel;
wire        wb_m2s_or1k_d_ledr0_we;
wire        wb_m2s_or1k_d_ledr0_cyc;
wire        wb_m2s_or1k_d_ledr0_stb;
wire  [2:0] wb_m2s_or1k_d_ledr0_cti;
wire  [1:0] wb_m2s_or1k_d_ledr0_bte;
wire [31:0] wb_s2m_or1k_d_ledr0_dat;
wire        wb_s2m_or1k_d_ledr0_ack;
wire        wb_s2m_or1k_d_ledr0_err;
wire        wb_s2m_or1k_d_ledr0_rty;
wire [31:0] wb_m2s_or1k_d_ledr1_adr;
wire [31:0] wb_m2s_or1k_d_ledr1_dat;
wire  [3:0] wb_m2s_or1k_d_ledr1_sel;
wire        wb_m2s_or1k_d_ledr1_we;
wire        wb_m2s_or1k_d_ledr1_cyc;
wire        wb_m2s_or1k_d_ledr1_stb;
wire  [2:0] wb_m2s_or1k_d_ledr1_cti;
wire  [1:0] wb_m2s_or1k_d_ledr1_bte;
wire [31:0] wb_s2m_or1k_d_ledr1_dat;
wire        wb_s2m_or1k_d_ledr1_ack;
wire        wb_s2m_or1k_d_ledr1_err;
wire        wb_s2m_or1k_d_ledr1_rty;
wire [31:0] wb_m2s_or1k_d_ledg0_adr;
wire [31:0] wb_m2s_or1k_d_ledg0_dat;
wire  [3:0] wb_m2s_or1k_d_ledg0_sel;
wire        wb_m2s_or1k_d_ledg0_we;
wire        wb_m2s_or1k_d_ledg0_cyc;
wire        wb_m2s_or1k_d_ledg0_stb;
wire  [2:0] wb_m2s_or1k_d_ledg0_cti;
wire  [1:0] wb_m2s_or1k_d_ledg0_bte;
wire [31:0] wb_s2m_or1k_d_ledg0_dat;
wire        wb_s2m_or1k_d_ledg0_ack;
wire        wb_s2m_or1k_d_ledg0_err;
wire        wb_s2m_or1k_d_ledg0_rty;
wire [31:0] wb_m2s_or1k_d_ledgr0_adr;
wire [31:0] wb_m2s_or1k_d_ledgr0_dat;
wire  [3:0] wb_m2s_or1k_d_ledgr0_sel;
wire        wb_m2s_or1k_d_ledgr0_we;
wire        wb_m2s_or1k_d_ledgr0_cyc;
wire        wb_m2s_or1k_d_ledgr0_stb;
wire  [2:0] wb_m2s_or1k_d_ledgr0_cti;
wire  [1:0] wb_m2s_or1k_d_ledgr0_bte;
wire [31:0] wb_s2m_or1k_d_ledgr0_dat;
wire        wb_s2m_or1k_d_ledgr0_ack;
wire        wb_s2m_or1k_d_ledgr0_err;
wire        wb_s2m_or1k_d_ledgr0_rty;
wire [31:0] wb_m2s_or1k_d_switch0_adr;
wire [31:0] wb_m2s_or1k_d_switch0_dat;
wire  [3:0] wb_m2s_or1k_d_switch0_sel;
wire        wb_m2s_or1k_d_switch0_we;
wire        wb_m2s_or1k_d_switch0_cyc;
wire        wb_m2s_or1k_d_switch0_stb;
wire  [2:0] wb_m2s_or1k_d_switch0_cti;
wire  [1:0] wb_m2s_or1k_d_switch0_bte;
wire [31:0] wb_s2m_or1k_d_switch0_dat;
wire        wb_s2m_or1k_d_switch0_ack;
wire        wb_s2m_or1k_d_switch0_err;
wire        wb_s2m_or1k_d_switch0_rty;
wire [31:0] wb_m2s_or1k_d_switch1_adr;
wire [31:0] wb_m2s_or1k_d_switch1_dat;
wire  [3:0] wb_m2s_or1k_d_switch1_sel;
wire        wb_m2s_or1k_d_switch1_we;
wire        wb_m2s_or1k_d_switch1_cyc;
wire        wb_m2s_or1k_d_switch1_stb;
wire  [2:0] wb_m2s_or1k_d_switch1_cti;
wire  [1:0] wb_m2s_or1k_d_switch1_bte;
wire [31:0] wb_s2m_or1k_d_switch1_dat;
wire        wb_s2m_or1k_d_switch1_ack;
wire        wb_s2m_or1k_d_switch1_err;
wire        wb_s2m_or1k_d_switch1_rty;
wire [31:0] wb_m2s_or1k_d_switch2_adr;
wire [31:0] wb_m2s_or1k_d_switch2_dat;
wire  [3:0] wb_m2s_or1k_d_switch2_sel;
wire        wb_m2s_or1k_d_switch2_we;
wire        wb_m2s_or1k_d_switch2_cyc;
wire        wb_m2s_or1k_d_switch2_stb;
wire  [2:0] wb_m2s_or1k_d_switch2_cti;
wire  [1:0] wb_m2s_or1k_d_switch2_bte;
wire [31:0] wb_s2m_or1k_d_switch2_dat;
wire        wb_s2m_or1k_d_switch2_ack;
wire        wb_s2m_or1k_d_switch2_err;
wire        wb_s2m_or1k_d_switch2_rty;
wire [31:0] wb_m2s_dbg_sdram_dbus_adr;
wire [31:0] wb_m2s_dbg_sdram_dbus_dat;
wire  [3:0] wb_m2s_dbg_sdram_dbus_sel;
wire        wb_m2s_dbg_sdram_dbus_we;
wire        wb_m2s_dbg_sdram_dbus_cyc;
wire        wb_m2s_dbg_sdram_dbus_stb;
wire  [2:0] wb_m2s_dbg_sdram_dbus_cti;
wire  [1:0] wb_m2s_dbg_sdram_dbus_bte;
wire [31:0] wb_s2m_dbg_sdram_dbus_dat;
wire        wb_s2m_dbg_sdram_dbus_ack;
wire        wb_s2m_dbg_sdram_dbus_err;
wire        wb_s2m_dbg_sdram_dbus_rty;
wire [31:0] wb_m2s_dbg_uart0_adr;
wire [31:0] wb_m2s_dbg_uart0_dat;
wire  [3:0] wb_m2s_dbg_uart0_sel;
wire        wb_m2s_dbg_uart0_we;
wire        wb_m2s_dbg_uart0_cyc;
wire        wb_m2s_dbg_uart0_stb;
wire  [2:0] wb_m2s_dbg_uart0_cti;
wire  [1:0] wb_m2s_dbg_uart0_bte;
wire [31:0] wb_s2m_dbg_uart0_dat;
wire        wb_s2m_dbg_uart0_ack;
wire        wb_s2m_dbg_uart0_err;
wire        wb_s2m_dbg_uart0_rty;
wire [31:0] wb_m2s_dbg_gpio0_adr;
wire [31:0] wb_m2s_dbg_gpio0_dat;
wire  [3:0] wb_m2s_dbg_gpio0_sel;
wire        wb_m2s_dbg_gpio0_we;
wire        wb_m2s_dbg_gpio0_cyc;
wire        wb_m2s_dbg_gpio0_stb;
wire  [2:0] wb_m2s_dbg_gpio0_cti;
wire  [1:0] wb_m2s_dbg_gpio0_bte;
wire [31:0] wb_s2m_dbg_gpio0_dat;
wire        wb_s2m_dbg_gpio0_ack;
wire        wb_s2m_dbg_gpio0_err;
wire        wb_s2m_dbg_gpio0_rty;
wire [31:0] wb_m2s_dbg_key_adr;
wire [31:0] wb_m2s_dbg_key_dat;
wire  [3:0] wb_m2s_dbg_key_sel;
wire        wb_m2s_dbg_key_we;
wire        wb_m2s_dbg_key_cyc;
wire        wb_m2s_dbg_key_stb;
wire  [2:0] wb_m2s_dbg_key_cti;
wire  [1:0] wb_m2s_dbg_key_bte;
wire [31:0] wb_s2m_dbg_key_dat;
wire        wb_s2m_dbg_key_ack;
wire        wb_s2m_dbg_key_err;
wire        wb_s2m_dbg_key_rty;
wire [31:0] wb_m2s_dbg_ledr0_adr;
wire [31:0] wb_m2s_dbg_ledr0_dat;
wire  [3:0] wb_m2s_dbg_ledr0_sel;
wire        wb_m2s_dbg_ledr0_we;
wire        wb_m2s_dbg_ledr0_cyc;
wire        wb_m2s_dbg_ledr0_stb;
wire  [2:0] wb_m2s_dbg_ledr0_cti;
wire  [1:0] wb_m2s_dbg_ledr0_bte;
wire [31:0] wb_s2m_dbg_ledr0_dat;
wire        wb_s2m_dbg_ledr0_ack;
wire        wb_s2m_dbg_ledr0_err;
wire        wb_s2m_dbg_ledr0_rty;
wire [31:0] wb_m2s_dbg_ledr1_adr;
wire [31:0] wb_m2s_dbg_ledr1_dat;
wire  [3:0] wb_m2s_dbg_ledr1_sel;
wire        wb_m2s_dbg_ledr1_we;
wire        wb_m2s_dbg_ledr1_cyc;
wire        wb_m2s_dbg_ledr1_stb;
wire  [2:0] wb_m2s_dbg_ledr1_cti;
wire  [1:0] wb_m2s_dbg_ledr1_bte;
wire [31:0] wb_s2m_dbg_ledr1_dat;
wire        wb_s2m_dbg_ledr1_ack;
wire        wb_s2m_dbg_ledr1_err;
wire        wb_s2m_dbg_ledr1_rty;
wire [31:0] wb_m2s_dbg_ledg0_adr;
wire [31:0] wb_m2s_dbg_ledg0_dat;
wire  [3:0] wb_m2s_dbg_ledg0_sel;
wire        wb_m2s_dbg_ledg0_we;
wire        wb_m2s_dbg_ledg0_cyc;
wire        wb_m2s_dbg_ledg0_stb;
wire  [2:0] wb_m2s_dbg_ledg0_cti;
wire  [1:0] wb_m2s_dbg_ledg0_bte;
wire [31:0] wb_s2m_dbg_ledg0_dat;
wire        wb_s2m_dbg_ledg0_ack;
wire        wb_s2m_dbg_ledg0_err;
wire        wb_s2m_dbg_ledg0_rty;
wire [31:0] wb_m2s_dbg_ledgr0_adr;
wire [31:0] wb_m2s_dbg_ledgr0_dat;
wire  [3:0] wb_m2s_dbg_ledgr0_sel;
wire        wb_m2s_dbg_ledgr0_we;
wire        wb_m2s_dbg_ledgr0_cyc;
wire        wb_m2s_dbg_ledgr0_stb;
wire  [2:0] wb_m2s_dbg_ledgr0_cti;
wire  [1:0] wb_m2s_dbg_ledgr0_bte;
wire [31:0] wb_s2m_dbg_ledgr0_dat;
wire        wb_s2m_dbg_ledgr0_ack;
wire        wb_s2m_dbg_ledgr0_err;
wire        wb_s2m_dbg_ledgr0_rty;
wire [31:0] wb_m2s_dbg_switch0_adr;
wire [31:0] wb_m2s_dbg_switch0_dat;
wire  [3:0] wb_m2s_dbg_switch0_sel;
wire        wb_m2s_dbg_switch0_we;
wire        wb_m2s_dbg_switch0_cyc;
wire        wb_m2s_dbg_switch0_stb;
wire  [2:0] wb_m2s_dbg_switch0_cti;
wire  [1:0] wb_m2s_dbg_switch0_bte;
wire [31:0] wb_s2m_dbg_switch0_dat;
wire        wb_s2m_dbg_switch0_ack;
wire        wb_s2m_dbg_switch0_err;
wire        wb_s2m_dbg_switch0_rty;
wire [31:0] wb_m2s_dbg_switch1_adr;
wire [31:0] wb_m2s_dbg_switch1_dat;
wire  [3:0] wb_m2s_dbg_switch1_sel;
wire        wb_m2s_dbg_switch1_we;
wire        wb_m2s_dbg_switch1_cyc;
wire        wb_m2s_dbg_switch1_stb;
wire  [2:0] wb_m2s_dbg_switch1_cti;
wire  [1:0] wb_m2s_dbg_switch1_bte;
wire [31:0] wb_s2m_dbg_switch1_dat;
wire        wb_s2m_dbg_switch1_ack;
wire        wb_s2m_dbg_switch1_err;
wire        wb_s2m_dbg_switch1_rty;
wire [31:0] wb_m2s_dbg_switch2_adr;
wire [31:0] wb_m2s_dbg_switch2_dat;
wire  [3:0] wb_m2s_dbg_switch2_sel;
wire        wb_m2s_dbg_switch2_we;
wire        wb_m2s_dbg_switch2_cyc;
wire        wb_m2s_dbg_switch2_stb;
wire  [2:0] wb_m2s_dbg_switch2_cti;
wire  [1:0] wb_m2s_dbg_switch2_bte;
wire [31:0] wb_s2m_dbg_switch2_dat;
wire        wb_s2m_dbg_switch2_ack;
wire        wb_s2m_dbg_switch2_err;
wire        wb_s2m_dbg_switch2_rty;
wire [31:0] wb_m2s_resize_uart0_adr;
wire [31:0] wb_m2s_resize_uart0_dat;
wire  [3:0] wb_m2s_resize_uart0_sel;
wire        wb_m2s_resize_uart0_we;
wire        wb_m2s_resize_uart0_cyc;
wire        wb_m2s_resize_uart0_stb;
wire  [2:0] wb_m2s_resize_uart0_cti;
wire  [1:0] wb_m2s_resize_uart0_bte;
wire [31:0] wb_s2m_resize_uart0_dat;
wire        wb_s2m_resize_uart0_ack;
wire        wb_s2m_resize_uart0_err;
wire        wb_s2m_resize_uart0_rty;
wire [31:0] wb_m2s_resize_gpio0_adr;
wire [31:0] wb_m2s_resize_gpio0_dat;
wire  [3:0] wb_m2s_resize_gpio0_sel;
wire        wb_m2s_resize_gpio0_we;
wire        wb_m2s_resize_gpio0_cyc;
wire        wb_m2s_resize_gpio0_stb;
wire  [2:0] wb_m2s_resize_gpio0_cti;
wire  [1:0] wb_m2s_resize_gpio0_bte;
wire [31:0] wb_s2m_resize_gpio0_dat;
wire        wb_s2m_resize_gpio0_ack;
wire        wb_s2m_resize_gpio0_err;
wire        wb_s2m_resize_gpio0_rty;
wire [31:0] wb_m2s_resize_switch0_adr;
wire [31:0] wb_m2s_resize_switch0_dat;
wire  [3:0] wb_m2s_resize_switch0_sel;
wire        wb_m2s_resize_switch0_we;
wire        wb_m2s_resize_switch0_cyc;
wire        wb_m2s_resize_switch0_stb;
wire  [2:0] wb_m2s_resize_switch0_cti;
wire  [1:0] wb_m2s_resize_switch0_bte;
wire [31:0] wb_s2m_resize_switch0_dat;
wire        wb_s2m_resize_switch0_ack;
wire        wb_s2m_resize_switch0_err;
wire        wb_s2m_resize_switch0_rty;
wire [31:0] wb_m2s_resize_switch1_adr;
wire [31:0] wb_m2s_resize_switch1_dat;
wire  [3:0] wb_m2s_resize_switch1_sel;
wire        wb_m2s_resize_switch1_we;
wire        wb_m2s_resize_switch1_cyc;
wire        wb_m2s_resize_switch1_stb;
wire  [2:0] wb_m2s_resize_switch1_cti;
wire  [1:0] wb_m2s_resize_switch1_bte;
wire [31:0] wb_s2m_resize_switch1_dat;
wire        wb_s2m_resize_switch1_ack;
wire        wb_s2m_resize_switch1_err;
wire        wb_s2m_resize_switch1_rty;
wire [31:0] wb_m2s_resize_switch2_adr;
wire [31:0] wb_m2s_resize_switch2_dat;
wire  [3:0] wb_m2s_resize_switch2_sel;
wire        wb_m2s_resize_switch2_we;
wire        wb_m2s_resize_switch2_cyc;
wire        wb_m2s_resize_switch2_stb;
wire  [2:0] wb_m2s_resize_switch2_cti;
wire  [1:0] wb_m2s_resize_switch2_bte;
wire [31:0] wb_s2m_resize_switch2_dat;
wire        wb_s2m_resize_switch2_ack;
wire        wb_s2m_resize_switch2_err;
wire        wb_s2m_resize_switch2_rty;
wire [31:0] wb_m2s_resize_key_adr;
wire [31:0] wb_m2s_resize_key_dat;
wire  [3:0] wb_m2s_resize_key_sel;
wire        wb_m2s_resize_key_we;
wire        wb_m2s_resize_key_cyc;
wire        wb_m2s_resize_key_stb;
wire  [2:0] wb_m2s_resize_key_cti;
wire  [1:0] wb_m2s_resize_key_bte;
wire [31:0] wb_s2m_resize_key_dat;
wire        wb_s2m_resize_key_ack;
wire        wb_s2m_resize_key_err;
wire        wb_s2m_resize_key_rty;
wire [31:0] wb_m2s_resize_ledr0_adr;
wire [31:0] wb_m2s_resize_ledr0_dat;
wire  [3:0] wb_m2s_resize_ledr0_sel;
wire        wb_m2s_resize_ledr0_we;
wire        wb_m2s_resize_ledr0_cyc;
wire        wb_m2s_resize_ledr0_stb;
wire  [2:0] wb_m2s_resize_ledr0_cti;
wire  [1:0] wb_m2s_resize_ledr0_bte;
wire [31:0] wb_s2m_resize_ledr0_dat;
wire        wb_s2m_resize_ledr0_ack;
wire        wb_s2m_resize_ledr0_err;
wire        wb_s2m_resize_ledr0_rty;
wire [31:0] wb_m2s_resize_ledr1_adr;
wire [31:0] wb_m2s_resize_ledr1_dat;
wire  [3:0] wb_m2s_resize_ledr1_sel;
wire        wb_m2s_resize_ledr1_we;
wire        wb_m2s_resize_ledr1_cyc;
wire        wb_m2s_resize_ledr1_stb;
wire  [2:0] wb_m2s_resize_ledr1_cti;
wire  [1:0] wb_m2s_resize_ledr1_bte;
wire [31:0] wb_s2m_resize_ledr1_dat;
wire        wb_s2m_resize_ledr1_ack;
wire        wb_s2m_resize_ledr1_err;
wire        wb_s2m_resize_ledr1_rty;
wire [31:0] wb_m2s_resize_ledg0_adr;
wire [31:0] wb_m2s_resize_ledg0_dat;
wire  [3:0] wb_m2s_resize_ledg0_sel;
wire        wb_m2s_resize_ledg0_we;
wire        wb_m2s_resize_ledg0_cyc;
wire        wb_m2s_resize_ledg0_stb;
wire  [2:0] wb_m2s_resize_ledg0_cti;
wire  [1:0] wb_m2s_resize_ledg0_bte;
wire [31:0] wb_s2m_resize_ledg0_dat;
wire        wb_s2m_resize_ledg0_ack;
wire        wb_s2m_resize_ledg0_err;
wire        wb_s2m_resize_ledg0_rty;
wire [31:0] wb_m2s_resize_ledgr0_adr;
wire [31:0] wb_m2s_resize_ledgr0_dat;
wire  [3:0] wb_m2s_resize_ledgr0_sel;
wire        wb_m2s_resize_ledgr0_we;
wire        wb_m2s_resize_ledgr0_cyc;
wire        wb_m2s_resize_ledgr0_stb;
wire  [2:0] wb_m2s_resize_ledgr0_cti;
wire  [1:0] wb_m2s_resize_ledgr0_bte;
wire [31:0] wb_s2m_resize_ledgr0_dat;
wire        wb_s2m_resize_ledgr0_ack;
wire        wb_s2m_resize_ledgr0_err;
wire        wb_s2m_resize_ledgr0_rty;

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h00000000, 32'hf0000000}),
    .MATCH_MASK ({32'hff800000, 32'hffffffc0}))
 wb_mux_or1k_i
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_i_adr_i),
    .wbm_dat_i (wb_or1k_i_dat_i),
    .wbm_sel_i (wb_or1k_i_sel_i),
    .wbm_we_i  (wb_or1k_i_we_i),
    .wbm_cyc_i (wb_or1k_i_cyc_i),
    .wbm_stb_i (wb_or1k_i_stb_i),
    .wbm_cti_i (wb_or1k_i_cti_i),
    .wbm_bte_i (wb_or1k_i_bte_i),
    .wbm_dat_o (wb_or1k_i_dat_o),
    .wbm_ack_o (wb_or1k_i_ack_o),
    .wbm_err_o (wb_or1k_i_err_o),
    .wbm_rty_o (wb_or1k_i_rty_o),
    .wbs_adr_o ({wb_sdram_ibus_adr_o, wb_rom0_adr_o}),
    .wbs_dat_o ({wb_sdram_ibus_dat_o, wb_rom0_dat_o}),
    .wbs_sel_o ({wb_sdram_ibus_sel_o, wb_rom0_sel_o}),
    .wbs_we_o  ({wb_sdram_ibus_we_o, wb_rom0_we_o}),
    .wbs_cyc_o ({wb_sdram_ibus_cyc_o, wb_rom0_cyc_o}),
    .wbs_stb_o ({wb_sdram_ibus_stb_o, wb_rom0_stb_o}),
    .wbs_cti_o ({wb_sdram_ibus_cti_o, wb_rom0_cti_o}),
    .wbs_bte_o ({wb_sdram_ibus_bte_o, wb_rom0_bte_o}),
    .wbs_dat_i ({wb_sdram_ibus_dat_i, wb_rom0_dat_i}),
    .wbs_ack_i ({wb_sdram_ibus_ack_i, wb_rom0_ack_i}),
    .wbs_err_i ({wb_sdram_ibus_err_i, wb_rom0_err_i}),
    .wbs_rty_i ({wb_sdram_ibus_rty_i, wb_rom0_rty_i}));

wb_mux
  #(.num_slaves (11),
    .MATCH_ADDR ({32'h00000000, 32'h90000000, 32'h91000000, 32'ha3000000, 32'h92000000, 32'h93000000, 32'h94000000, 32'h95000000, 32'ha0000000, 32'ha1000000, 32'ha2000000}),
    .MATCH_MASK ({32'hff800000, 32'hffffffe0, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe}))
 wb_mux_or1k_d
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_d_adr_i),
    .wbm_dat_i (wb_or1k_d_dat_i),
    .wbm_sel_i (wb_or1k_d_sel_i),
    .wbm_we_i  (wb_or1k_d_we_i),
    .wbm_cyc_i (wb_or1k_d_cyc_i),
    .wbm_stb_i (wb_or1k_d_stb_i),
    .wbm_cti_i (wb_or1k_d_cti_i),
    .wbm_bte_i (wb_or1k_d_bte_i),
    .wbm_dat_o (wb_or1k_d_dat_o),
    .wbm_ack_o (wb_or1k_d_ack_o),
    .wbm_err_o (wb_or1k_d_err_o),
    .wbm_rty_o (wb_or1k_d_rty_o),
    .wbs_adr_o ({wb_m2s_or1k_d_sdram_dbus_adr, wb_m2s_or1k_d_uart0_adr, wb_m2s_or1k_d_gpio0_adr, wb_m2s_or1k_d_key_adr, wb_m2s_or1k_d_ledr0_adr, wb_m2s_or1k_d_ledr1_adr, wb_m2s_or1k_d_ledg0_adr, wb_m2s_or1k_d_ledgr0_adr, wb_m2s_or1k_d_switch0_adr, wb_m2s_or1k_d_switch1_adr, wb_m2s_or1k_d_switch2_adr}),
    .wbs_dat_o ({wb_m2s_or1k_d_sdram_dbus_dat, wb_m2s_or1k_d_uart0_dat, wb_m2s_or1k_d_gpio0_dat, wb_m2s_or1k_d_key_dat, wb_m2s_or1k_d_ledr0_dat, wb_m2s_or1k_d_ledr1_dat, wb_m2s_or1k_d_ledg0_dat, wb_m2s_or1k_d_ledgr0_dat, wb_m2s_or1k_d_switch0_dat, wb_m2s_or1k_d_switch1_dat, wb_m2s_or1k_d_switch2_dat}),
    .wbs_sel_o ({wb_m2s_or1k_d_sdram_dbus_sel, wb_m2s_or1k_d_uart0_sel, wb_m2s_or1k_d_gpio0_sel, wb_m2s_or1k_d_key_sel, wb_m2s_or1k_d_ledr0_sel, wb_m2s_or1k_d_ledr1_sel, wb_m2s_or1k_d_ledg0_sel, wb_m2s_or1k_d_ledgr0_sel, wb_m2s_or1k_d_switch0_sel, wb_m2s_or1k_d_switch1_sel, wb_m2s_or1k_d_switch2_sel}),
    .wbs_we_o  ({wb_m2s_or1k_d_sdram_dbus_we, wb_m2s_or1k_d_uart0_we, wb_m2s_or1k_d_gpio0_we, wb_m2s_or1k_d_key_we, wb_m2s_or1k_d_ledr0_we, wb_m2s_or1k_d_ledr1_we, wb_m2s_or1k_d_ledg0_we, wb_m2s_or1k_d_ledgr0_we, wb_m2s_or1k_d_switch0_we, wb_m2s_or1k_d_switch1_we, wb_m2s_or1k_d_switch2_we}),
    .wbs_cyc_o ({wb_m2s_or1k_d_sdram_dbus_cyc, wb_m2s_or1k_d_uart0_cyc, wb_m2s_or1k_d_gpio0_cyc, wb_m2s_or1k_d_key_cyc, wb_m2s_or1k_d_ledr0_cyc, wb_m2s_or1k_d_ledr1_cyc, wb_m2s_or1k_d_ledg0_cyc, wb_m2s_or1k_d_ledgr0_cyc, wb_m2s_or1k_d_switch0_cyc, wb_m2s_or1k_d_switch1_cyc, wb_m2s_or1k_d_switch2_cyc}),
    .wbs_stb_o ({wb_m2s_or1k_d_sdram_dbus_stb, wb_m2s_or1k_d_uart0_stb, wb_m2s_or1k_d_gpio0_stb, wb_m2s_or1k_d_key_stb, wb_m2s_or1k_d_ledr0_stb, wb_m2s_or1k_d_ledr1_stb, wb_m2s_or1k_d_ledg0_stb, wb_m2s_or1k_d_ledgr0_stb, wb_m2s_or1k_d_switch0_stb, wb_m2s_or1k_d_switch1_stb, wb_m2s_or1k_d_switch2_stb}),
    .wbs_cti_o ({wb_m2s_or1k_d_sdram_dbus_cti, wb_m2s_or1k_d_uart0_cti, wb_m2s_or1k_d_gpio0_cti, wb_m2s_or1k_d_key_cti, wb_m2s_or1k_d_ledr0_cti, wb_m2s_or1k_d_ledr1_cti, wb_m2s_or1k_d_ledg0_cti, wb_m2s_or1k_d_ledgr0_cti, wb_m2s_or1k_d_switch0_cti, wb_m2s_or1k_d_switch1_cti, wb_m2s_or1k_d_switch2_cti}),
    .wbs_bte_o ({wb_m2s_or1k_d_sdram_dbus_bte, wb_m2s_or1k_d_uart0_bte, wb_m2s_or1k_d_gpio0_bte, wb_m2s_or1k_d_key_bte, wb_m2s_or1k_d_ledr0_bte, wb_m2s_or1k_d_ledr1_bte, wb_m2s_or1k_d_ledg0_bte, wb_m2s_or1k_d_ledgr0_bte, wb_m2s_or1k_d_switch0_bte, wb_m2s_or1k_d_switch1_bte, wb_m2s_or1k_d_switch2_bte}),
    .wbs_dat_i ({wb_s2m_or1k_d_sdram_dbus_dat, wb_s2m_or1k_d_uart0_dat, wb_s2m_or1k_d_gpio0_dat, wb_s2m_or1k_d_key_dat, wb_s2m_or1k_d_ledr0_dat, wb_s2m_or1k_d_ledr1_dat, wb_s2m_or1k_d_ledg0_dat, wb_s2m_or1k_d_ledgr0_dat, wb_s2m_or1k_d_switch0_dat, wb_s2m_or1k_d_switch1_dat, wb_s2m_or1k_d_switch2_dat}),
    .wbs_ack_i ({wb_s2m_or1k_d_sdram_dbus_ack, wb_s2m_or1k_d_uart0_ack, wb_s2m_or1k_d_gpio0_ack, wb_s2m_or1k_d_key_ack, wb_s2m_or1k_d_ledr0_ack, wb_s2m_or1k_d_ledr1_ack, wb_s2m_or1k_d_ledg0_ack, wb_s2m_or1k_d_ledgr0_ack, wb_s2m_or1k_d_switch0_ack, wb_s2m_or1k_d_switch1_ack, wb_s2m_or1k_d_switch2_ack}),
    .wbs_err_i ({wb_s2m_or1k_d_sdram_dbus_err, wb_s2m_or1k_d_uart0_err, wb_s2m_or1k_d_gpio0_err, wb_s2m_or1k_d_key_err, wb_s2m_or1k_d_ledr0_err, wb_s2m_or1k_d_ledr1_err, wb_s2m_or1k_d_ledg0_err, wb_s2m_or1k_d_ledgr0_err, wb_s2m_or1k_d_switch0_err, wb_s2m_or1k_d_switch1_err, wb_s2m_or1k_d_switch2_err}),
    .wbs_rty_i ({wb_s2m_or1k_d_sdram_dbus_rty, wb_s2m_or1k_d_uart0_rty, wb_s2m_or1k_d_gpio0_rty, wb_s2m_or1k_d_key_rty, wb_s2m_or1k_d_ledr0_rty, wb_s2m_or1k_d_ledr1_rty, wb_s2m_or1k_d_ledg0_rty, wb_s2m_or1k_d_ledgr0_rty, wb_s2m_or1k_d_switch0_rty, wb_s2m_or1k_d_switch1_rty, wb_s2m_or1k_d_switch2_rty}));

wb_mux
  #(.num_slaves (11),
    .MATCH_ADDR ({32'h00000000, 32'h90000000, 32'h91000000, 32'ha3000000, 32'h92000000, 32'h93000000, 32'h94000000, 32'h95000000, 32'ha0000000, 32'ha1000000, 32'ha2000000}),
    .MATCH_MASK ({32'hff800000, 32'hffffffe0, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe, 32'hfffffffe}))
 wb_mux_dbg
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dbg_adr_i),
    .wbm_dat_i (wb_dbg_dat_i),
    .wbm_sel_i (wb_dbg_sel_i),
    .wbm_we_i  (wb_dbg_we_i),
    .wbm_cyc_i (wb_dbg_cyc_i),
    .wbm_stb_i (wb_dbg_stb_i),
    .wbm_cti_i (wb_dbg_cti_i),
    .wbm_bte_i (wb_dbg_bte_i),
    .wbm_dat_o (wb_dbg_dat_o),
    .wbm_ack_o (wb_dbg_ack_o),
    .wbm_err_o (wb_dbg_err_o),
    .wbm_rty_o (wb_dbg_rty_o),
    .wbs_adr_o ({wb_m2s_dbg_sdram_dbus_adr, wb_m2s_dbg_uart0_adr, wb_m2s_dbg_gpio0_adr, wb_m2s_dbg_key_adr, wb_m2s_dbg_ledr0_adr, wb_m2s_dbg_ledr1_adr, wb_m2s_dbg_ledg0_adr, wb_m2s_dbg_ledgr0_adr, wb_m2s_dbg_switch0_adr, wb_m2s_dbg_switch1_adr, wb_m2s_dbg_switch2_adr}),
    .wbs_dat_o ({wb_m2s_dbg_sdram_dbus_dat, wb_m2s_dbg_uart0_dat, wb_m2s_dbg_gpio0_dat, wb_m2s_dbg_key_dat, wb_m2s_dbg_ledr0_dat, wb_m2s_dbg_ledr1_dat, wb_m2s_dbg_ledg0_dat, wb_m2s_dbg_ledgr0_dat, wb_m2s_dbg_switch0_dat, wb_m2s_dbg_switch1_dat, wb_m2s_dbg_switch2_dat}),
    .wbs_sel_o ({wb_m2s_dbg_sdram_dbus_sel, wb_m2s_dbg_uart0_sel, wb_m2s_dbg_gpio0_sel, wb_m2s_dbg_key_sel, wb_m2s_dbg_ledr0_sel, wb_m2s_dbg_ledr1_sel, wb_m2s_dbg_ledg0_sel, wb_m2s_dbg_ledgr0_sel, wb_m2s_dbg_switch0_sel, wb_m2s_dbg_switch1_sel, wb_m2s_dbg_switch2_sel}),
    .wbs_we_o  ({wb_m2s_dbg_sdram_dbus_we, wb_m2s_dbg_uart0_we, wb_m2s_dbg_gpio0_we, wb_m2s_dbg_key_we, wb_m2s_dbg_ledr0_we, wb_m2s_dbg_ledr1_we, wb_m2s_dbg_ledg0_we, wb_m2s_dbg_ledgr0_we, wb_m2s_dbg_switch0_we, wb_m2s_dbg_switch1_we, wb_m2s_dbg_switch2_we}),
    .wbs_cyc_o ({wb_m2s_dbg_sdram_dbus_cyc, wb_m2s_dbg_uart0_cyc, wb_m2s_dbg_gpio0_cyc, wb_m2s_dbg_key_cyc, wb_m2s_dbg_ledr0_cyc, wb_m2s_dbg_ledr1_cyc, wb_m2s_dbg_ledg0_cyc, wb_m2s_dbg_ledgr0_cyc, wb_m2s_dbg_switch0_cyc, wb_m2s_dbg_switch1_cyc, wb_m2s_dbg_switch2_cyc}),
    .wbs_stb_o ({wb_m2s_dbg_sdram_dbus_stb, wb_m2s_dbg_uart0_stb, wb_m2s_dbg_gpio0_stb, wb_m2s_dbg_key_stb, wb_m2s_dbg_ledr0_stb, wb_m2s_dbg_ledr1_stb, wb_m2s_dbg_ledg0_stb, wb_m2s_dbg_ledgr0_stb, wb_m2s_dbg_switch0_stb, wb_m2s_dbg_switch1_stb, wb_m2s_dbg_switch2_stb}),
    .wbs_cti_o ({wb_m2s_dbg_sdram_dbus_cti, wb_m2s_dbg_uart0_cti, wb_m2s_dbg_gpio0_cti, wb_m2s_dbg_key_cti, wb_m2s_dbg_ledr0_cti, wb_m2s_dbg_ledr1_cti, wb_m2s_dbg_ledg0_cti, wb_m2s_dbg_ledgr0_cti, wb_m2s_dbg_switch0_cti, wb_m2s_dbg_switch1_cti, wb_m2s_dbg_switch2_cti}),
    .wbs_bte_o ({wb_m2s_dbg_sdram_dbus_bte, wb_m2s_dbg_uart0_bte, wb_m2s_dbg_gpio0_bte, wb_m2s_dbg_key_bte, wb_m2s_dbg_ledr0_bte, wb_m2s_dbg_ledr1_bte, wb_m2s_dbg_ledg0_bte, wb_m2s_dbg_ledgr0_bte, wb_m2s_dbg_switch0_bte, wb_m2s_dbg_switch1_bte, wb_m2s_dbg_switch2_bte}),
    .wbs_dat_i ({wb_s2m_dbg_sdram_dbus_dat, wb_s2m_dbg_uart0_dat, wb_s2m_dbg_gpio0_dat, wb_s2m_dbg_key_dat, wb_s2m_dbg_ledr0_dat, wb_s2m_dbg_ledr1_dat, wb_s2m_dbg_ledg0_dat, wb_s2m_dbg_ledgr0_dat, wb_s2m_dbg_switch0_dat, wb_s2m_dbg_switch1_dat, wb_s2m_dbg_switch2_dat}),
    .wbs_ack_i ({wb_s2m_dbg_sdram_dbus_ack, wb_s2m_dbg_uart0_ack, wb_s2m_dbg_gpio0_ack, wb_s2m_dbg_key_ack, wb_s2m_dbg_ledr0_ack, wb_s2m_dbg_ledr1_ack, wb_s2m_dbg_ledg0_ack, wb_s2m_dbg_ledgr0_ack, wb_s2m_dbg_switch0_ack, wb_s2m_dbg_switch1_ack, wb_s2m_dbg_switch2_ack}),
    .wbs_err_i ({wb_s2m_dbg_sdram_dbus_err, wb_s2m_dbg_uart0_err, wb_s2m_dbg_gpio0_err, wb_s2m_dbg_key_err, wb_s2m_dbg_ledr0_err, wb_s2m_dbg_ledr1_err, wb_s2m_dbg_ledg0_err, wb_s2m_dbg_ledgr0_err, wb_s2m_dbg_switch0_err, wb_s2m_dbg_switch1_err, wb_s2m_dbg_switch2_err}),
    .wbs_rty_i ({wb_s2m_dbg_sdram_dbus_rty, wb_s2m_dbg_uart0_rty, wb_s2m_dbg_gpio0_rty, wb_s2m_dbg_key_rty, wb_s2m_dbg_ledr0_rty, wb_s2m_dbg_ledr1_rty, wb_s2m_dbg_ledg0_rty, wb_s2m_dbg_ledgr0_rty, wb_s2m_dbg_switch0_rty, wb_s2m_dbg_switch1_rty, wb_s2m_dbg_switch2_rty}));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_uart0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_uart0_adr, wb_m2s_dbg_uart0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_uart0_dat, wb_m2s_dbg_uart0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_uart0_sel, wb_m2s_dbg_uart0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_uart0_we, wb_m2s_dbg_uart0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_uart0_cyc, wb_m2s_dbg_uart0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_uart0_stb, wb_m2s_dbg_uart0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_uart0_cti, wb_m2s_dbg_uart0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_uart0_bte, wb_m2s_dbg_uart0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_uart0_dat, wb_s2m_dbg_uart0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_uart0_ack, wb_s2m_dbg_uart0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_uart0_err, wb_s2m_dbg_uart0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_uart0_rty, wb_s2m_dbg_uart0_rty}),
    .wbs_adr_o (wb_m2s_resize_uart0_adr),
    .wbs_dat_o (wb_m2s_resize_uart0_dat),
    .wbs_sel_o (wb_m2s_resize_uart0_sel),
    .wbs_we_o  (wb_m2s_resize_uart0_we),
    .wbs_cyc_o (wb_m2s_resize_uart0_cyc),
    .wbs_stb_o (wb_m2s_resize_uart0_stb),
    .wbs_cti_o (wb_m2s_resize_uart0_cti),
    .wbs_bte_o (wb_m2s_resize_uart0_bte),
    .wbs_dat_i (wb_s2m_resize_uart0_dat),
    .wbs_ack_i (wb_s2m_resize_uart0_ack),
    .wbs_err_i (wb_s2m_resize_uart0_err),
    .wbs_rty_i (wb_s2m_resize_uart0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_uart0
   (.wbm_adr_i (wb_m2s_resize_uart0_adr),
    .wbm_dat_i (wb_m2s_resize_uart0_dat),
    .wbm_sel_i (wb_m2s_resize_uart0_sel),
    .wbm_we_i  (wb_m2s_resize_uart0_we),
    .wbm_cyc_i (wb_m2s_resize_uart0_cyc),
    .wbm_stb_i (wb_m2s_resize_uart0_stb),
    .wbm_cti_i (wb_m2s_resize_uart0_cti),
    .wbm_bte_i (wb_m2s_resize_uart0_bte),
    .wbm_dat_o (wb_s2m_resize_uart0_dat),
    .wbm_ack_o (wb_s2m_resize_uart0_ack),
    .wbm_err_o (wb_s2m_resize_uart0_err),
    .wbm_rty_o (wb_s2m_resize_uart0_rty),
    .wbs_adr_o (wb_uart0_adr_o),
    .wbs_dat_o (wb_uart0_dat_o),
    .wbs_we_o  (wb_uart0_we_o),
    .wbs_cyc_o (wb_uart0_cyc_o),
    .wbs_stb_o (wb_uart0_stb_o),
    .wbs_cti_o (wb_uart0_cti_o),
    .wbs_bte_o (wb_uart0_bte_o),
    .wbs_dat_i (wb_uart0_dat_i),
    .wbs_ack_i (wb_uart0_ack_i),
    .wbs_err_i (wb_uart0_err_i),
    .wbs_rty_i (wb_uart0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_gpio0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio0_adr, wb_m2s_dbg_gpio0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio0_dat, wb_m2s_dbg_gpio0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio0_sel, wb_m2s_dbg_gpio0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio0_we, wb_m2s_dbg_gpio0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio0_cyc, wb_m2s_dbg_gpio0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio0_stb, wb_m2s_dbg_gpio0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio0_cti, wb_m2s_dbg_gpio0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio0_bte, wb_m2s_dbg_gpio0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio0_dat, wb_s2m_dbg_gpio0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio0_ack, wb_s2m_dbg_gpio0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio0_err, wb_s2m_dbg_gpio0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio0_rty, wb_s2m_dbg_gpio0_rty}),
    .wbs_adr_o (wb_m2s_resize_gpio0_adr),
    .wbs_dat_o (wb_m2s_resize_gpio0_dat),
    .wbs_sel_o (wb_m2s_resize_gpio0_sel),
    .wbs_we_o  (wb_m2s_resize_gpio0_we),
    .wbs_cyc_o (wb_m2s_resize_gpio0_cyc),
    .wbs_stb_o (wb_m2s_resize_gpio0_stb),
    .wbs_cti_o (wb_m2s_resize_gpio0_cti),
    .wbs_bte_o (wb_m2s_resize_gpio0_bte),
    .wbs_dat_i (wb_s2m_resize_gpio0_dat),
    .wbs_ack_i (wb_s2m_resize_gpio0_ack),
    .wbs_err_i (wb_s2m_resize_gpio0_err),
    .wbs_rty_i (wb_s2m_resize_gpio0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_gpio0
   (.wbm_adr_i (wb_m2s_resize_gpio0_adr),
    .wbm_dat_i (wb_m2s_resize_gpio0_dat),
    .wbm_sel_i (wb_m2s_resize_gpio0_sel),
    .wbm_we_i  (wb_m2s_resize_gpio0_we),
    .wbm_cyc_i (wb_m2s_resize_gpio0_cyc),
    .wbm_stb_i (wb_m2s_resize_gpio0_stb),
    .wbm_cti_i (wb_m2s_resize_gpio0_cti),
    .wbm_bte_i (wb_m2s_resize_gpio0_bte),
    .wbm_dat_o (wb_s2m_resize_gpio0_dat),
    .wbm_ack_o (wb_s2m_resize_gpio0_ack),
    .wbm_err_o (wb_s2m_resize_gpio0_err),
    .wbm_rty_o (wb_s2m_resize_gpio0_rty),
    .wbs_adr_o (wb_gpio0_adr_o),
    .wbs_dat_o (wb_gpio0_dat_o),
    .wbs_we_o  (wb_gpio0_we_o),
    .wbs_cyc_o (wb_gpio0_cyc_o),
    .wbs_stb_o (wb_gpio0_stb_o),
    .wbs_cti_o (wb_gpio0_cti_o),
    .wbs_bte_o (wb_gpio0_bte_o),
    .wbs_dat_i (wb_gpio0_dat_i),
    .wbs_ack_i (wb_gpio0_ack_i),
    .wbs_err_i (wb_gpio0_err_i),
    .wbs_rty_i (wb_gpio0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_switch0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_switch0_adr, wb_m2s_dbg_switch0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_switch0_dat, wb_m2s_dbg_switch0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_switch0_sel, wb_m2s_dbg_switch0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_switch0_we, wb_m2s_dbg_switch0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_switch0_cyc, wb_m2s_dbg_switch0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_switch0_stb, wb_m2s_dbg_switch0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_switch0_cti, wb_m2s_dbg_switch0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_switch0_bte, wb_m2s_dbg_switch0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_switch0_dat, wb_s2m_dbg_switch0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_switch0_ack, wb_s2m_dbg_switch0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_switch0_err, wb_s2m_dbg_switch0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_switch0_rty, wb_s2m_dbg_switch0_rty}),
    .wbs_adr_o (wb_m2s_resize_switch0_adr),
    .wbs_dat_o (wb_m2s_resize_switch0_dat),
    .wbs_sel_o (wb_m2s_resize_switch0_sel),
    .wbs_we_o  (wb_m2s_resize_switch0_we),
    .wbs_cyc_o (wb_m2s_resize_switch0_cyc),
    .wbs_stb_o (wb_m2s_resize_switch0_stb),
    .wbs_cti_o (wb_m2s_resize_switch0_cti),
    .wbs_bte_o (wb_m2s_resize_switch0_bte),
    .wbs_dat_i (wb_s2m_resize_switch0_dat),
    .wbs_ack_i (wb_s2m_resize_switch0_ack),
    .wbs_err_i (wb_s2m_resize_switch0_err),
    .wbs_rty_i (wb_s2m_resize_switch0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_switch0
   (.wbm_adr_i (wb_m2s_resize_switch0_adr),
    .wbm_dat_i (wb_m2s_resize_switch0_dat),
    .wbm_sel_i (wb_m2s_resize_switch0_sel),
    .wbm_we_i  (wb_m2s_resize_switch0_we),
    .wbm_cyc_i (wb_m2s_resize_switch0_cyc),
    .wbm_stb_i (wb_m2s_resize_switch0_stb),
    .wbm_cti_i (wb_m2s_resize_switch0_cti),
    .wbm_bte_i (wb_m2s_resize_switch0_bte),
    .wbm_dat_o (wb_s2m_resize_switch0_dat),
    .wbm_ack_o (wb_s2m_resize_switch0_ack),
    .wbm_err_o (wb_s2m_resize_switch0_err),
    .wbm_rty_o (wb_s2m_resize_switch0_rty),
    .wbs_adr_o (wb_switch0_adr_o),
    .wbs_dat_o (wb_switch0_dat_o),
    .wbs_we_o  (wb_switch0_we_o),
    .wbs_cyc_o (wb_switch0_cyc_o),
    .wbs_stb_o (wb_switch0_stb_o),
    .wbs_cti_o (wb_switch0_cti_o),
    .wbs_bte_o (wb_switch0_bte_o),
    .wbs_dat_i (wb_switch0_dat_i),
    .wbs_ack_i (wb_switch0_ack_i),
    .wbs_err_i (wb_switch0_err_i),
    .wbs_rty_i (wb_switch0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_switch1
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_switch1_adr, wb_m2s_dbg_switch1_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_switch1_dat, wb_m2s_dbg_switch1_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_switch1_sel, wb_m2s_dbg_switch1_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_switch1_we, wb_m2s_dbg_switch1_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_switch1_cyc, wb_m2s_dbg_switch1_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_switch1_stb, wb_m2s_dbg_switch1_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_switch1_cti, wb_m2s_dbg_switch1_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_switch1_bte, wb_m2s_dbg_switch1_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_switch1_dat, wb_s2m_dbg_switch1_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_switch1_ack, wb_s2m_dbg_switch1_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_switch1_err, wb_s2m_dbg_switch1_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_switch1_rty, wb_s2m_dbg_switch1_rty}),
    .wbs_adr_o (wb_m2s_resize_switch1_adr),
    .wbs_dat_o (wb_m2s_resize_switch1_dat),
    .wbs_sel_o (wb_m2s_resize_switch1_sel),
    .wbs_we_o  (wb_m2s_resize_switch1_we),
    .wbs_cyc_o (wb_m2s_resize_switch1_cyc),
    .wbs_stb_o (wb_m2s_resize_switch1_stb),
    .wbs_cti_o (wb_m2s_resize_switch1_cti),
    .wbs_bte_o (wb_m2s_resize_switch1_bte),
    .wbs_dat_i (wb_s2m_resize_switch1_dat),
    .wbs_ack_i (wb_s2m_resize_switch1_ack),
    .wbs_err_i (wb_s2m_resize_switch1_err),
    .wbs_rty_i (wb_s2m_resize_switch1_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_switch1
   (.wbm_adr_i (wb_m2s_resize_switch1_adr),
    .wbm_dat_i (wb_m2s_resize_switch1_dat),
    .wbm_sel_i (wb_m2s_resize_switch1_sel),
    .wbm_we_i  (wb_m2s_resize_switch1_we),
    .wbm_cyc_i (wb_m2s_resize_switch1_cyc),
    .wbm_stb_i (wb_m2s_resize_switch1_stb),
    .wbm_cti_i (wb_m2s_resize_switch1_cti),
    .wbm_bte_i (wb_m2s_resize_switch1_bte),
    .wbm_dat_o (wb_s2m_resize_switch1_dat),
    .wbm_ack_o (wb_s2m_resize_switch1_ack),
    .wbm_err_o (wb_s2m_resize_switch1_err),
    .wbm_rty_o (wb_s2m_resize_switch1_rty),
    .wbs_adr_o (wb_switch1_adr_o),
    .wbs_dat_o (wb_switch1_dat_o),
    .wbs_we_o  (wb_switch1_we_o),
    .wbs_cyc_o (wb_switch1_cyc_o),
    .wbs_stb_o (wb_switch1_stb_o),
    .wbs_cti_o (wb_switch1_cti_o),
    .wbs_bte_o (wb_switch1_bte_o),
    .wbs_dat_i (wb_switch1_dat_i),
    .wbs_ack_i (wb_switch1_ack_i),
    .wbs_err_i (wb_switch1_err_i),
    .wbs_rty_i (wb_switch1_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_switch2
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_switch2_adr, wb_m2s_dbg_switch2_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_switch2_dat, wb_m2s_dbg_switch2_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_switch2_sel, wb_m2s_dbg_switch2_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_switch2_we, wb_m2s_dbg_switch2_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_switch2_cyc, wb_m2s_dbg_switch2_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_switch2_stb, wb_m2s_dbg_switch2_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_switch2_cti, wb_m2s_dbg_switch2_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_switch2_bte, wb_m2s_dbg_switch2_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_switch2_dat, wb_s2m_dbg_switch2_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_switch2_ack, wb_s2m_dbg_switch2_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_switch2_err, wb_s2m_dbg_switch2_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_switch2_rty, wb_s2m_dbg_switch2_rty}),
    .wbs_adr_o (wb_m2s_resize_switch2_adr),
    .wbs_dat_o (wb_m2s_resize_switch2_dat),
    .wbs_sel_o (wb_m2s_resize_switch2_sel),
    .wbs_we_o  (wb_m2s_resize_switch2_we),
    .wbs_cyc_o (wb_m2s_resize_switch2_cyc),
    .wbs_stb_o (wb_m2s_resize_switch2_stb),
    .wbs_cti_o (wb_m2s_resize_switch2_cti),
    .wbs_bte_o (wb_m2s_resize_switch2_bte),
    .wbs_dat_i (wb_s2m_resize_switch2_dat),
    .wbs_ack_i (wb_s2m_resize_switch2_ack),
    .wbs_err_i (wb_s2m_resize_switch2_err),
    .wbs_rty_i (wb_s2m_resize_switch2_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_switch2
   (.wbm_adr_i (wb_m2s_resize_switch2_adr),
    .wbm_dat_i (wb_m2s_resize_switch2_dat),
    .wbm_sel_i (wb_m2s_resize_switch2_sel),
    .wbm_we_i  (wb_m2s_resize_switch2_we),
    .wbm_cyc_i (wb_m2s_resize_switch2_cyc),
    .wbm_stb_i (wb_m2s_resize_switch2_stb),
    .wbm_cti_i (wb_m2s_resize_switch2_cti),
    .wbm_bte_i (wb_m2s_resize_switch2_bte),
    .wbm_dat_o (wb_s2m_resize_switch2_dat),
    .wbm_ack_o (wb_s2m_resize_switch2_ack),
    .wbm_err_o (wb_s2m_resize_switch2_err),
    .wbm_rty_o (wb_s2m_resize_switch2_rty),
    .wbs_adr_o (wb_switch2_adr_o),
    .wbs_dat_o (wb_switch2_dat_o),
    .wbs_we_o  (wb_switch2_we_o),
    .wbs_cyc_o (wb_switch2_cyc_o),
    .wbs_stb_o (wb_switch2_stb_o),
    .wbs_cti_o (wb_switch2_cti_o),
    .wbs_bte_o (wb_switch2_bte_o),
    .wbs_dat_i (wb_switch2_dat_i),
    .wbs_ack_i (wb_switch2_ack_i),
    .wbs_err_i (wb_switch2_err_i),
    .wbs_rty_i (wb_switch2_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_key
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_key_adr, wb_m2s_dbg_key_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_key_dat, wb_m2s_dbg_key_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_key_sel, wb_m2s_dbg_key_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_key_we, wb_m2s_dbg_key_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_key_cyc, wb_m2s_dbg_key_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_key_stb, wb_m2s_dbg_key_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_key_cti, wb_m2s_dbg_key_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_key_bte, wb_m2s_dbg_key_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_key_dat, wb_s2m_dbg_key_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_key_ack, wb_s2m_dbg_key_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_key_err, wb_s2m_dbg_key_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_key_rty, wb_s2m_dbg_key_rty}),
    .wbs_adr_o (wb_m2s_resize_key_adr),
    .wbs_dat_o (wb_m2s_resize_key_dat),
    .wbs_sel_o (wb_m2s_resize_key_sel),
    .wbs_we_o  (wb_m2s_resize_key_we),
    .wbs_cyc_o (wb_m2s_resize_key_cyc),
    .wbs_stb_o (wb_m2s_resize_key_stb),
    .wbs_cti_o (wb_m2s_resize_key_cti),
    .wbs_bte_o (wb_m2s_resize_key_bte),
    .wbs_dat_i (wb_s2m_resize_key_dat),
    .wbs_ack_i (wb_s2m_resize_key_ack),
    .wbs_err_i (wb_s2m_resize_key_err),
    .wbs_rty_i (wb_s2m_resize_key_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_key
   (.wbm_adr_i (wb_m2s_resize_key_adr),
    .wbm_dat_i (wb_m2s_resize_key_dat),
    .wbm_sel_i (wb_m2s_resize_key_sel),
    .wbm_we_i  (wb_m2s_resize_key_we),
    .wbm_cyc_i (wb_m2s_resize_key_cyc),
    .wbm_stb_i (wb_m2s_resize_key_stb),
    .wbm_cti_i (wb_m2s_resize_key_cti),
    .wbm_bte_i (wb_m2s_resize_key_bte),
    .wbm_dat_o (wb_s2m_resize_key_dat),
    .wbm_ack_o (wb_s2m_resize_key_ack),
    .wbm_err_o (wb_s2m_resize_key_err),
    .wbm_rty_o (wb_s2m_resize_key_rty),
    .wbs_adr_o (wb_key_adr_o),
    .wbs_dat_o (wb_key_dat_o),
    .wbs_we_o  (wb_key_we_o),
    .wbs_cyc_o (wb_key_cyc_o),
    .wbs_stb_o (wb_key_stb_o),
    .wbs_cti_o (wb_key_cti_o),
    .wbs_bte_o (wb_key_bte_o),
    .wbs_dat_i (wb_key_dat_i),
    .wbs_ack_i (wb_key_ack_i),
    .wbs_err_i (wb_key_err_i),
    .wbs_rty_i (wb_key_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_ledr0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ledr0_adr, wb_m2s_dbg_ledr0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ledr0_dat, wb_m2s_dbg_ledr0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ledr0_sel, wb_m2s_dbg_ledr0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ledr0_we, wb_m2s_dbg_ledr0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ledr0_cyc, wb_m2s_dbg_ledr0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ledr0_stb, wb_m2s_dbg_ledr0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ledr0_cti, wb_m2s_dbg_ledr0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ledr0_bte, wb_m2s_dbg_ledr0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ledr0_dat, wb_s2m_dbg_ledr0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ledr0_ack, wb_s2m_dbg_ledr0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ledr0_err, wb_s2m_dbg_ledr0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ledr0_rty, wb_s2m_dbg_ledr0_rty}),
    .wbs_adr_o (wb_m2s_resize_ledr0_adr),
    .wbs_dat_o (wb_m2s_resize_ledr0_dat),
    .wbs_sel_o (wb_m2s_resize_ledr0_sel),
    .wbs_we_o  (wb_m2s_resize_ledr0_we),
    .wbs_cyc_o (wb_m2s_resize_ledr0_cyc),
    .wbs_stb_o (wb_m2s_resize_ledr0_stb),
    .wbs_cti_o (wb_m2s_resize_ledr0_cti),
    .wbs_bte_o (wb_m2s_resize_ledr0_bte),
    .wbs_dat_i (wb_s2m_resize_ledr0_dat),
    .wbs_ack_i (wb_s2m_resize_ledr0_ack),
    .wbs_err_i (wb_s2m_resize_ledr0_err),
    .wbs_rty_i (wb_s2m_resize_ledr0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_ledr0
   (.wbm_adr_i (wb_m2s_resize_ledr0_adr),
    .wbm_dat_i (wb_m2s_resize_ledr0_dat),
    .wbm_sel_i (wb_m2s_resize_ledr0_sel),
    .wbm_we_i  (wb_m2s_resize_ledr0_we),
    .wbm_cyc_i (wb_m2s_resize_ledr0_cyc),
    .wbm_stb_i (wb_m2s_resize_ledr0_stb),
    .wbm_cti_i (wb_m2s_resize_ledr0_cti),
    .wbm_bte_i (wb_m2s_resize_ledr0_bte),
    .wbm_dat_o (wb_s2m_resize_ledr0_dat),
    .wbm_ack_o (wb_s2m_resize_ledr0_ack),
    .wbm_err_o (wb_s2m_resize_ledr0_err),
    .wbm_rty_o (wb_s2m_resize_ledr0_rty),
    .wbs_adr_o (wb_ledr0_adr_o),
    .wbs_dat_o (wb_ledr0_dat_o),
    .wbs_we_o  (wb_ledr0_we_o),
    .wbs_cyc_o (wb_ledr0_cyc_o),
    .wbs_stb_o (wb_ledr0_stb_o),
    .wbs_cti_o (wb_ledr0_cti_o),
    .wbs_bte_o (wb_ledr0_bte_o),
    .wbs_dat_i (wb_ledr0_dat_i),
    .wbs_ack_i (wb_ledr0_ack_i),
    .wbs_err_i (wb_ledr0_err_i),
    .wbs_rty_i (wb_ledr0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_ledr1
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ledr1_adr, wb_m2s_dbg_ledr1_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ledr1_dat, wb_m2s_dbg_ledr1_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ledr1_sel, wb_m2s_dbg_ledr1_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ledr1_we, wb_m2s_dbg_ledr1_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ledr1_cyc, wb_m2s_dbg_ledr1_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ledr1_stb, wb_m2s_dbg_ledr1_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ledr1_cti, wb_m2s_dbg_ledr1_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ledr1_bte, wb_m2s_dbg_ledr1_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ledr1_dat, wb_s2m_dbg_ledr1_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ledr1_ack, wb_s2m_dbg_ledr1_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ledr1_err, wb_s2m_dbg_ledr1_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ledr1_rty, wb_s2m_dbg_ledr1_rty}),
    .wbs_adr_o (wb_m2s_resize_ledr1_adr),
    .wbs_dat_o (wb_m2s_resize_ledr1_dat),
    .wbs_sel_o (wb_m2s_resize_ledr1_sel),
    .wbs_we_o  (wb_m2s_resize_ledr1_we),
    .wbs_cyc_o (wb_m2s_resize_ledr1_cyc),
    .wbs_stb_o (wb_m2s_resize_ledr1_stb),
    .wbs_cti_o (wb_m2s_resize_ledr1_cti),
    .wbs_bte_o (wb_m2s_resize_ledr1_bte),
    .wbs_dat_i (wb_s2m_resize_ledr1_dat),
    .wbs_ack_i (wb_s2m_resize_ledr1_ack),
    .wbs_err_i (wb_s2m_resize_ledr1_err),
    .wbs_rty_i (wb_s2m_resize_ledr1_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_ledr1
   (.wbm_adr_i (wb_m2s_resize_ledr1_adr),
    .wbm_dat_i (wb_m2s_resize_ledr1_dat),
    .wbm_sel_i (wb_m2s_resize_ledr1_sel),
    .wbm_we_i  (wb_m2s_resize_ledr1_we),
    .wbm_cyc_i (wb_m2s_resize_ledr1_cyc),
    .wbm_stb_i (wb_m2s_resize_ledr1_stb),
    .wbm_cti_i (wb_m2s_resize_ledr1_cti),
    .wbm_bte_i (wb_m2s_resize_ledr1_bte),
    .wbm_dat_o (wb_s2m_resize_ledr1_dat),
    .wbm_ack_o (wb_s2m_resize_ledr1_ack),
    .wbm_err_o (wb_s2m_resize_ledr1_err),
    .wbm_rty_o (wb_s2m_resize_ledr1_rty),
    .wbs_adr_o (wb_ledr1_adr_o),
    .wbs_dat_o (wb_ledr1_dat_o),
    .wbs_we_o  (wb_ledr1_we_o),
    .wbs_cyc_o (wb_ledr1_cyc_o),
    .wbs_stb_o (wb_ledr1_stb_o),
    .wbs_cti_o (wb_ledr1_cti_o),
    .wbs_bte_o (wb_ledr1_bte_o),
    .wbs_dat_i (wb_ledr1_dat_i),
    .wbs_ack_i (wb_ledr1_ack_i),
    .wbs_err_i (wb_ledr1_err_i),
    .wbs_rty_i (wb_ledr1_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_ledg0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ledg0_adr, wb_m2s_dbg_ledg0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ledg0_dat, wb_m2s_dbg_ledg0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ledg0_sel, wb_m2s_dbg_ledg0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ledg0_we, wb_m2s_dbg_ledg0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ledg0_cyc, wb_m2s_dbg_ledg0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ledg0_stb, wb_m2s_dbg_ledg0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ledg0_cti, wb_m2s_dbg_ledg0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ledg0_bte, wb_m2s_dbg_ledg0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ledg0_dat, wb_s2m_dbg_ledg0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ledg0_ack, wb_s2m_dbg_ledg0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ledg0_err, wb_s2m_dbg_ledg0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ledg0_rty, wb_s2m_dbg_ledg0_rty}),
    .wbs_adr_o (wb_m2s_resize_ledg0_adr),
    .wbs_dat_o (wb_m2s_resize_ledg0_dat),
    .wbs_sel_o (wb_m2s_resize_ledg0_sel),
    .wbs_we_o  (wb_m2s_resize_ledg0_we),
    .wbs_cyc_o (wb_m2s_resize_ledg0_cyc),
    .wbs_stb_o (wb_m2s_resize_ledg0_stb),
    .wbs_cti_o (wb_m2s_resize_ledg0_cti),
    .wbs_bte_o (wb_m2s_resize_ledg0_bte),
    .wbs_dat_i (wb_s2m_resize_ledg0_dat),
    .wbs_ack_i (wb_s2m_resize_ledg0_ack),
    .wbs_err_i (wb_s2m_resize_ledg0_err),
    .wbs_rty_i (wb_s2m_resize_ledg0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_ledg0
   (.wbm_adr_i (wb_m2s_resize_ledg0_adr),
    .wbm_dat_i (wb_m2s_resize_ledg0_dat),
    .wbm_sel_i (wb_m2s_resize_ledg0_sel),
    .wbm_we_i  (wb_m2s_resize_ledg0_we),
    .wbm_cyc_i (wb_m2s_resize_ledg0_cyc),
    .wbm_stb_i (wb_m2s_resize_ledg0_stb),
    .wbm_cti_i (wb_m2s_resize_ledg0_cti),
    .wbm_bte_i (wb_m2s_resize_ledg0_bte),
    .wbm_dat_o (wb_s2m_resize_ledg0_dat),
    .wbm_ack_o (wb_s2m_resize_ledg0_ack),
    .wbm_err_o (wb_s2m_resize_ledg0_err),
    .wbm_rty_o (wb_s2m_resize_ledg0_rty),
    .wbs_adr_o (wb_ledg0_adr_o),
    .wbs_dat_o (wb_ledg0_dat_o),
    .wbs_we_o  (wb_ledg0_we_o),
    .wbs_cyc_o (wb_ledg0_cyc_o),
    .wbs_stb_o (wb_ledg0_stb_o),
    .wbs_cti_o (wb_ledg0_cti_o),
    .wbs_bte_o (wb_ledg0_bte_o),
    .wbs_dat_i (wb_ledg0_dat_i),
    .wbs_ack_i (wb_ledg0_ack_i),
    .wbs_err_i (wb_ledg0_err_i),
    .wbs_rty_i (wb_ledg0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_ledgr0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ledgr0_adr, wb_m2s_dbg_ledgr0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ledgr0_dat, wb_m2s_dbg_ledgr0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ledgr0_sel, wb_m2s_dbg_ledgr0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ledgr0_we, wb_m2s_dbg_ledgr0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ledgr0_cyc, wb_m2s_dbg_ledgr0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ledgr0_stb, wb_m2s_dbg_ledgr0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ledgr0_cti, wb_m2s_dbg_ledgr0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ledgr0_bte, wb_m2s_dbg_ledgr0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ledgr0_dat, wb_s2m_dbg_ledgr0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ledgr0_ack, wb_s2m_dbg_ledgr0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ledgr0_err, wb_s2m_dbg_ledgr0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ledgr0_rty, wb_s2m_dbg_ledgr0_rty}),
    .wbs_adr_o (wb_m2s_resize_ledgr0_adr),
    .wbs_dat_o (wb_m2s_resize_ledgr0_dat),
    .wbs_sel_o (wb_m2s_resize_ledgr0_sel),
    .wbs_we_o  (wb_m2s_resize_ledgr0_we),
    .wbs_cyc_o (wb_m2s_resize_ledgr0_cyc),
    .wbs_stb_o (wb_m2s_resize_ledgr0_stb),
    .wbs_cti_o (wb_m2s_resize_ledgr0_cti),
    .wbs_bte_o (wb_m2s_resize_ledgr0_bte),
    .wbs_dat_i (wb_s2m_resize_ledgr0_dat),
    .wbs_ack_i (wb_s2m_resize_ledgr0_ack),
    .wbs_err_i (wb_s2m_resize_ledgr0_err),
    .wbs_rty_i (wb_s2m_resize_ledgr0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_ledgr0
   (.wbm_adr_i (wb_m2s_resize_ledgr0_adr),
    .wbm_dat_i (wb_m2s_resize_ledgr0_dat),
    .wbm_sel_i (wb_m2s_resize_ledgr0_sel),
    .wbm_we_i  (wb_m2s_resize_ledgr0_we),
    .wbm_cyc_i (wb_m2s_resize_ledgr0_cyc),
    .wbm_stb_i (wb_m2s_resize_ledgr0_stb),
    .wbm_cti_i (wb_m2s_resize_ledgr0_cti),
    .wbm_bte_i (wb_m2s_resize_ledgr0_bte),
    .wbm_dat_o (wb_s2m_resize_ledgr0_dat),
    .wbm_ack_o (wb_s2m_resize_ledgr0_ack),
    .wbm_err_o (wb_s2m_resize_ledgr0_err),
    .wbm_rty_o (wb_s2m_resize_ledgr0_rty),
    .wbs_adr_o (wb_ledgr0_adr_o),
    .wbs_dat_o (wb_ledgr0_dat_o),
    .wbs_we_o  (wb_ledgr0_we_o),
    .wbs_cyc_o (wb_ledgr0_cyc_o),
    .wbs_stb_o (wb_ledgr0_stb_o),
    .wbs_cti_o (wb_ledgr0_cti_o),
    .wbs_bte_o (wb_ledgr0_bte_o),
    .wbs_dat_i (wb_ledgr0_dat_i),
    .wbs_ack_i (wb_ledgr0_ack_i),
    .wbs_err_i (wb_ledgr0_err_i),
    .wbs_rty_i (wb_ledgr0_rty_i));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_sdram_dbus
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_sdram_dbus_adr, wb_m2s_dbg_sdram_dbus_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_sdram_dbus_dat, wb_m2s_dbg_sdram_dbus_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_sdram_dbus_sel, wb_m2s_dbg_sdram_dbus_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_sdram_dbus_we, wb_m2s_dbg_sdram_dbus_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_sdram_dbus_cyc, wb_m2s_dbg_sdram_dbus_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_sdram_dbus_stb, wb_m2s_dbg_sdram_dbus_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_sdram_dbus_cti, wb_m2s_dbg_sdram_dbus_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_sdram_dbus_bte, wb_m2s_dbg_sdram_dbus_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_sdram_dbus_dat, wb_s2m_dbg_sdram_dbus_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_sdram_dbus_ack, wb_s2m_dbg_sdram_dbus_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_sdram_dbus_err, wb_s2m_dbg_sdram_dbus_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_sdram_dbus_rty, wb_s2m_dbg_sdram_dbus_rty}),
    .wbs_adr_o (wb_sdram_dbus_adr_o),
    .wbs_dat_o (wb_sdram_dbus_dat_o),
    .wbs_sel_o (wb_sdram_dbus_sel_o),
    .wbs_we_o  (wb_sdram_dbus_we_o),
    .wbs_cyc_o (wb_sdram_dbus_cyc_o),
    .wbs_stb_o (wb_sdram_dbus_stb_o),
    .wbs_cti_o (wb_sdram_dbus_cti_o),
    .wbs_bte_o (wb_sdram_dbus_bte_o),
    .wbs_dat_i (wb_sdram_dbus_dat_i),
    .wbs_ack_i (wb_sdram_dbus_ack_i),
    .wbs_err_i (wb_sdram_dbus_err_i),
    .wbs_rty_i (wb_sdram_dbus_rty_i));

endmodule
